# Placeholder content per brand (varinpat-style). USER TO VERIFY/REPLACE real metrics later.
# All metrics marked placeholder — flagged with HTML comment in generated pages.
BRANDS = {
    "the-bloom": {
        "name": "The Bloom Clinic", "category": "aesthetic", "slug": "the-bloom",
        "logo": "thebloom",
        "desc": "คลินิกความงาม ที่เราวางคอนเทนต์ให้ภาพลักษณ์อบอุ่น น่าเชื่อถือ และเข้าถึงง่าย",
        "label": "Aesthetic Clinic · Content & Social",
        "stat_num": "2.1M", "stat_txt": "total views", "stat_2": "+120% engagement",
        "results": [
            ("2.1M", "Total Views", "ยอดวิวรวมจากทุกแพลตฟอร์ม"),
            ("+120%", "Engagement", "เพิ่มขึ้นกว่าเท่าตัวเมื่อเทียบก่อนเริ่มงาน"),
            ("2.3×", "Online Booking", "การจองออนไลน์เพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์ทั่วไป ไม่มีจุดยืนแบรนด์ที่ชัดเจน",
        "after": "ภาพลักษณ์อบอุ่นน่าเชื่อถือ สื่อสารต่อเนื่อง สร้าง trust ผ่านรีวิวจริง",
        "tags": ["Content Strategy", "Brand Identity", "Social Management", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "สร้าง", "work_heading_en": "trust",
    },
    "dr-fern": {
        "name": "Dr. Fern Clinic", "category": "aesthetic", "slug": "dr-fern",
        "logo": "dr-fern",
        "desc": "คลินิกความงาม ที่เราดันหมอเป็นแบรนด์ และสื่อสารความเชี่ยวชาญให้เข้าถึงกลุ่มเป้าหมาย",
        "label": "Aesthetic Clinic · Doctor Branding",
        "stat_num": "1.5M", "stat_txt": "total views", "stat_2": "+90% engagement",
        "results": [
            ("1.5M", "Total Views", "ยอดวิวรวมตลอดแคมเปญ"),
            ("+90%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("2×", "Online Booking", "การจองออนไลน์เพิ่มขึ้น"),
        ],
        "before": "หมอยังไม่เป็นที่รู้จัก คอนเทนต์ไม่ต่อเนื่อง",
        "after": "ดันหมอเป็นแบรนด์ สื่อสารความเชี่ยวชาญ สร้างความเชื่อมั่น",
        "tags": ["Doctor Branding", "Content Strategy", "Mood & Tone", "Performance Ads"],
        "work_heading_th": "ดันหมอ", "work_heading_accent": "เป็นแบรนด์", "work_heading_en": "",
    },
    "la-clair": {
        "name": "La Clair Clinic", "category": "aesthetic", "slug": "la-clair",
        "logo": "la-claire",
        "desc": "คลินิกความงาม ที่เราวางภาพลักษณ์พรีเมียมให้เข้าถึงกลุ่มลูกค้ากำลังซื้อสูง",
        "label": "Aesthetic Clinic · Content & Ads",
        "stat_num": "1.7M", "stat_txt": "total views", "stat_2": "+100% engagement",
        "results": [
            ("1.7M", "Total Views", "ยอดวิวรวมจากทุกแพลตฟอร์ม"),
            ("+100%", "Engagement", "เพิ่มขึ้นกว่าเท่าตัว"),
            ("2.2×", "Online Booking", "การจองออนไลน์เพิ่มขึ้น"),
        ],
        "before": "ภาพลักษณ์ยังไม่ชัด จับกลุ่มกว้างเกินไป",
        "after": "ภาพลักษณ์พรีเมียม จับกลุ่มลูกค้ากำลังซื้อสูง",
        "tags": ["Repositioning", "Content Strategy", "Mood & Tone", "Performance Ads"],
        "work_heading_th": "ภาพลักษณ์", "work_heading_accent": "พรีเมียม", "work_heading_en": "",
    },
    "pun-smile": {
        "name": "Pun Smile Dental Clinic", "category": "dental", "slug": "pun-smile",
        "logo": "punsmile",
        "desc": "คลินิกทันตกรรม ที่เราสร้างคอนเทนต์ให้เข้าถึงง่ายและสื่อสารความน่าเชื่อถือ",
        "label": "Dental Clinic · Content & Ads",
        "stat_num": "1.3M", "stat_txt": "total views", "stat_2": "+85% engagement",
        "results": [
            ("1.3M", "Total Views", "ยอดวิวรวมตลอดแคมเปญ"),
            ("+85%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("2×", "Online Booking", "การนัดหมายออนไลน์เพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์เข้าถึงยาก ภาพลักษณ์ไม่ชัด",
        "after": "คอนเทนต์เข้าถึงง่าย สื่อสารความน่าเชื่อถือของคลินิก",
        "tags": ["Content Strategy", "Brand Identity", "Social Management", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "เข้าถึงง่าย", "work_heading_en": "",
    },
    "klear": {
        "name": "Klear Clinic", "category": "aesthetic", "slug": "klear",
        "logo": "klear",
        "desc": "คลินิกความงาม ที่เราวางกลยุทธ์คอนเทนต์ให้เข้าถึงกลุ่มกำลังซื้อสูง",
        "label": "Aesthetic Clinic · Content & Ads",
        "stat_num": "1.6M", "stat_txt": "total views", "stat_2": "+95% engagement",
        "results": [
            ("1.6M", "Total Views", "ยอดวิวรวมจากทุกแพลตฟอร์ม"),
            ("+95%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("2.1×", "Online Booking", "การจองออนไลน์เพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์ไม่ต่อเนื่อง ภาพลักษณ์ยังไม่นิ่ง",
        "after": "วางกลยุทธ์คอนเทนต์ใหม่ จับกลุ่มกำลังซื้อสูง",
        "tags": ["Content Strategy", "Mood & Tone", "Doctor Branding", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "ใช่", "work_heading_en": "",
    },
}
