# Placeholder content per brand (varinpat-style). USER TO VERIFY/REPLACE real metrics later.
# All metrics marked placeholder — flagged with HTML comment in generated pages.
BRANDS = {
    "the-bloom": {
        "name": "The Bloom Clinic", "category": "aesthetic", "slug": "the-bloom",
        "logo": "thebloom",
        "desc": "คลินิกความงาม ที่เราวางคอนเทนต์ให้ภาพลักษณ์อบอุ่น น่าเชื่อถือ และเข้าถึงง่าย",
        "label": "Aesthetic Clinic · Content & Social",
        "stat_num": "2.1M", "stat_txt": "total views", "stat_2": "+120% engagement",
        "results": [
            ("2.1M", "Total Views", "ยอดวิวรวมจากทุกแพลตฟอร์ม"),
            ("+120%", "Engagement", "เพิ่มขึ้นกว่าเท่าตัวเมื่อเทียบก่อนเริ่มงาน"),
            ("2.3×", "Online Booking", "การจองออนไลน์เพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์ทั่วไป ไม่มีจุดยืนแบรนด์ที่ชัดเจน",
        "after": "ภาพลักษณ์อบอุ่นน่าเชื่อถือ สื่อสารต่อเนื่อง สร้าง trust ผ่านรีวิวจริง",
        "tags": ["Content Strategy", "Brand Identity", "Social Management", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "สร้าง", "work_heading_en": "trust",
    },
    "dr-fern": {
        "name": "Dr. Fern Clinic", "category": "aesthetic", "slug": "dr-fern",
        "logo": "dr-fern",
        "desc": "คลินิกความงาม ที่เราดันหมอเป็นแบรนด์ และสื่อสารความเชี่ยวชาญให้เข้าถึงกลุ่มเป้าหมาย",
        "label": "Aesthetic Clinic · Doctor Branding",
        "stat_num": "1.5M", "stat_txt": "total views", "stat_2": "+90% engagement",
        "results": [
            ("1.5M", "Total Views", "ยอดวิวรวมตลอดแคมเปญ"),
            ("+90%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("2×", "Online Booking", "การจองออนไลน์เพิ่มขึ้น"),
        ],
        "before": "หมอยังไม่เป็นที่รู้จัก คอนเทนต์ไม่ต่อเนื่อง",
        "after": "ดันหมอเป็นแบรนด์ สื่อสารความเชี่ยวชาญ สร้างความเชื่อมั่น",
        "tags": ["Doctor Branding", "Content Strategy", "Mood & Tone", "Performance Ads"],
        "work_heading_th": "ดันหมอ", "work_heading_accent": "เป็นแบรนด์", "work_heading_en": "",
    },
    "la-clair": {
        "name": "La Clair Clinic", "category": "aesthetic", "slug": "la-clair",
        "logo": "la-claire",
        "desc": "คลินิกความงาม ที่เราวางภาพลักษณ์พรีเมียมให้เข้าถึงกลุ่มลูกค้ากำลังซื้อสูง",
        "label": "Aesthetic Clinic · Content & Ads",
        "stat_num": "1.7M", "stat_txt": "total views", "stat_2": "+100% engagement",
        "results": [
            ("1.7M", "Total Views", "ยอดวิวรวมจากทุกแพลตฟอร์ม"),
            ("+100%", "Engagement", "เพิ่มขึ้นกว่าเท่าตัว"),
            ("2.2×", "Online Booking", "การจองออนไลน์เพิ่มขึ้น"),
        ],
        "before": "ภาพลักษณ์ยังไม่ชัด จับกลุ่มกว้างเกินไป",
        "after": "ภาพลักษณ์พรีเมียม จับกลุ่มลูกค้ากำลังซื้อสูง",
        "tags": ["Repositioning", "Content Strategy", "Mood & Tone", "Performance Ads"],
        "work_heading_th": "ภาพลักษณ์", "work_heading_accent": "พรีเมียม", "work_heading_en": "",
    },
    "pun-smile": {
        "name": "Pun Smile Dental Clinic", "category": "dental", "slug": "pun-smile",
        "logo": "punsmile",
        "desc": "คลินิกทันตกรรม ที่เราสร้างคอนเทนต์ให้เข้าถึงง่ายและสื่อสารความน่าเชื่อถือ",
        "label": "Dental Clinic · Content & Ads",
        "stat_num": "1.3M", "stat_txt": "total views", "stat_2": "+85% engagement",
        "results": [
            ("1.3M", "Total Views", "ยอดวิวรวมตลอดแคมเปญ"),
            ("+85%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("2×", "Online Booking", "การนัดหมายออนไลน์เพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์เข้าถึงยาก ภาพลักษณ์ไม่ชัด",
        "after": "คอนเทนต์เข้าถึงง่าย สื่อสารความน่าเชื่อถือของคลินิก",
        "tags": ["Content Strategy", "Brand Identity", "Social Management", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "เข้าถึงง่าย", "work_heading_en": "",
    },
    "klear": {
        "name": "Klear Clinic", "category": "aesthetic", "slug": "klear",
        "logo": "klear",
        "desc": "คลินิกความงาม ที่เราวางกลยุทธ์คอนเทนต์ให้เข้าถึงกลุ่มกำลังซื้อสูง",
        "label": "Aesthetic Clinic · Content & Ads",
        "stat_num": "1.6M", "stat_txt": "total views", "stat_2": "+95% engagement",
        "results": [
            ("1.6M", "Total Views", "ยอดวิวรวมจากทุกแพลตฟอร์ม"),
            ("+95%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("2.1×", "Online Booking", "การจองออนไลน์เพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์ไม่ต่อเนื่อง ภาพลักษณ์ยังไม่นิ่ง",
        "after": "วางกลยุทธ์คอนเทนต์ใหม่ จับกลุ่มกำลังซื้อสูง",
        "tags": ["Content Strategy", "Mood & Tone", "Doctor Branding", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "ใช่", "work_heading_en": "",
    },
    "samitivej": {
        "name": "Samitivej", "category": "wellness", "slug": "samitivej",
        "logo": "samitivej",
        "desc": "เวลเนสคลินิก ที่เราสร้างคอนเทนต์เชิงลึกด้าน longevity ให้เข้าถึงกลุ่มลูกค้าพรีเมียม",
        "label": "Wellness Clinic · Content & Ads",
        "stat_num": "1.4M", "stat_txt": "total views", "stat_2": "+80% engagement",
        "results": [
            ("1.4M", "Total Views", "ยอดวิวรวมจากทุกแพลตฟอร์ม"),
            ("+80%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("1.9×", "Online Booking", "การจองออนไลน์เพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์เชิงวิชาการเข้าใจยาก เข้าถึงกลุ่มเป้าหมายได้จำกัด",
        "after": "คอนเทนต์เชิงลึกที่เข้าใจง่าย สร้างความน่าเชื่อถือระดับพรีเมียม",
        "tags": ["Content Strategy", "Education Content", "Social Management", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "น่าเชื่อถือ", "work_heading_en": "",
    },
    "bangkok-dental": {
        "name": "Bangkok Dental Studio", "category": "dental", "slug": "bangkok-dental",
        "logo": "bangkok-dental",
        "desc": "คลินิกทันตกรรม ที่เราสร้างคอนเทนต์ให้ดูพรีเมียมและน่าเชื่อถือ",
        "label": "Dental Clinic · Content & Ads",
        "stat_num": "900K", "stat_txt": "total views", "stat_2": "+70% engagement",
        "results": [
            ("900K", "Total Views", "ยอดวิวรวมตลอดแคมเปญ"),
            ("+70%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("1.8×", "Online Booking", "การนัดหมายออนไลน์เพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์ไม่ต่อเนื่อง ภาพลักษณ์ยังไม่ชัดเจน",
        "after": "ภาพลักษณ์พรีเมียม คอนเทนต์สม่ำเสมอ น่าเชื่อถือ",
        "tags": ["Content Strategy", "Brand Identity", "Social Management", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "น่าเชื่อถือ", "work_heading_en": "",
    },
    "double-b": {
        "name": "Double B", "category": "dental", "slug": "double-b",
        "logo": "double-b",
        "desc": "คลินิกทันตกรรม ที่เราสร้างคอนเทนต์ให้ความรู้เข้าใจง่ายเรื่องทันตกรรม",
        "label": "Dental Clinic · Content & Ads",
        "stat_num": "800K", "stat_txt": "total views", "stat_2": "+65% engagement",
        "results": [
            ("800K", "Total Views", "ยอดวิวรวมตลอดแคมเปญ"),
            ("+65%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("1.7×", "Online Booking", "การนัดหมายออนไลน์เพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์ให้ความรู้ยังไม่ครอบคลุม เข้าถึงยาก",
        "after": "คอนเทนต์ให้ความรู้ครบถ้วน เข้าใจง่าย เข้าถึงกลุ่มเป้าหมายตรงจุด",
        "tags": ["Educational Content", "Content Strategy", "Social Management", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "เข้าใจง่าย", "work_heading_en": "",
    },
    "chaba": {
        "name": "Chaba Clinic", "category": "aesthetic", "slug": "chaba",
        "logo": "chaba",
        "desc": "คลินิกความงาม ที่เราสร้างคอนเทนต์ให้ความรู้และรีวิวที่เข้าถึงกลุ่มเป้าหมาย",
        "label": "Aesthetic Clinic · Content & Ads",
        "stat_num": "1.1M", "stat_txt": "total views", "stat_2": "+75% engagement",
        "results": [
            ("1.1M", "Total Views", "ยอดวิวรวมจากทุกแพลตฟอร์ม"),
            ("+75%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("1.9×", "Online Booking", "การจองออนไลน์เพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์ไม่ต่อเนื่อง ขาดความชัดเจนด้านบริการ",
        "after": "คอนเทนต์ให้ความรู้ + รีวิวจริง สร้างความมั่นใจให้ลูกค้า",
        "tags": ["Content Strategy", "Educational Content", "Social Management", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "มั่นใจ", "work_heading_en": "",
    },
    "so-on": {
        "name": "So On Clinic", "category": "aesthetic", "slug": "so-on",
        "logo": "so-on",
        "desc": "คลินิกความงาม ที่เราสร้างคอนเทนต์รีวิวจริงและให้ความรู้เรื่องหัตถการ",
        "label": "Aesthetic Clinic · Content & Ads",
        "stat_num": "1.2M", "stat_txt": "total views", "stat_2": "+90% engagement",
        "results": [
            ("1.2M", "Total Views", "ยอดวิวรวมจากทุกแพลตฟอร์ม"),
            ("+90%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("2×", "Online Booking", "การจองออนไลน์เพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์ขายตรงเกินไป ไม่สร้างความไว้วางใจ",
        "after": "คอนเทนต์รีวิวจริง + ให้ความรู้ สร้างความไว้วางใจระยะยาว",
        "tags": ["Content Strategy", "Educational Content", "Social Management", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "ไว้วางใจ", "work_heading_en": "",
    },
    "blink-babe": {
        "name": "Blink Babe", "category": "other", "slug": "blink-babe",
        "logo": "blink-babe",
        "desc": "แบรนด์ความงาม ที่เราสร้างคอนเทนต์โปรโมชั่นและรีวิวให้เข้าถึงกลุ่มลูกค้าใหม่",
        "label": "Beauty Brand · Content & Ads",
        "stat_num": "700K", "stat_txt": "total views", "stat_2": "+60% engagement",
        "results": [
            ("700K", "Total Views", "ยอดวิวรวมตลอดแคมเปญ"),
            ("+60%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("1.6×", "Bookings", "การจองเพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์โปรโมชั่นเข้าถึงกลุ่มเป้าหมายจำกัด",
        "after": "คอนเทนต์โปรโมชั่น + รีวิว เข้าถึงกลุ่มลูกค้าใหม่ต่อเนื่อง",
        "tags": ["Content Strategy", "Promotion", "Social Management", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "เข้าถึง", "work_heading_en": "",
    },
    "keeree": {
        "name": "Keeree", "category": "other", "slug": "keeree",
        "logo": "keeree",
        "desc": "แบรนด์ไลฟ์สไตล์ ที่เราสร้างคอนเทนต์เล่าเรื่องแบรนด์ให้มีเอกลักษณ์",
        "label": "Lifestyle Brand · Content & Ads",
        "stat_num": "650K", "stat_txt": "total views", "stat_2": "+70% engagement",
        "results": [
            ("650K", "Total Views", "ยอดวิวรวมตลอดแคมเปญ"),
            ("+70%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("1.7×", "Inquiries", "ยอดทักเข้ามาเพิ่มขึ้น"),
        ],
        "before": "แบรนด์ยังไม่มีเอกลักษณ์ชัดเจนในสื่อออนไลน์",
        "after": "คอนเทนต์เล่าเรื่องแบรนด์ที่มีเอกลักษณ์ จดจำง่าย",
        "tags": ["Brand Storytelling", "Content Strategy", "Social Management", "Performance Ads"],
        "work_heading_th": "เรื่องราวที่ ", "work_heading_accent": "จดจำ", "work_heading_en": "",
    },
    "the-attic": {
        "name": "The Attic", "category": "other", "slug": "the-attic",
        "logo": "the-attic",
        "desc": "ร้านอาหาร ที่เราสร้างคอนเทนต์ไลฟ์สไตล์ให้เข้าถึงกลุ่มลูกค้าในพื้นที่",
        "label": "Restaurant · Content & Ads",
        "stat_num": "600K", "stat_txt": "total views", "stat_2": "+55% engagement",
        "results": [
            ("600K", "Total Views", "ยอดวิวรวมตลอดแคมเปญ"),
            ("+55%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("1.5×", "Foot Traffic", "ลูกค้าเข้าร้านเพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์ไม่ต่อเนื่อง เข้าถึงกลุ่มลูกค้าในพื้นที่จำกัด",
        "after": "คอนเทนต์ไลฟ์สไตล์สม่ำเสมอ เข้าถึงกลุ่มลูกค้าในพื้นที่ต่อเนื่อง",
        "tags": ["Content Strategy", "Social Management", "Local Marketing", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "ใกล้ตัว", "work_heading_en": "",
    },
    "youyen": {
        "name": "Youyen", "category": "wellness", "slug": "youyen",
        "logo": "youyen",
        "desc": "เวลเนสคลินิก ที่เราสร้างคอนเทนต์ podcast และรีวิวให้เข้าถึงกลุ่มลูกค้าที่ใส่ใจสุขภาพ",
        "label": "Wellness Clinic · Content & Ads",
        "stat_num": "1M", "stat_txt": "total views", "stat_2": "+70% engagement",
        "results": [
            ("1M", "Total Views", "ยอดวิวรวมจากทุกแพลตฟอร์ม"),
            ("+70%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("1.8×", "Online Booking", "การจองออนไลน์เพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์เชิงวิชาการเข้าใจยาก ไม่มีความต่อเนื่อง",
        "after": "คอนเทนต์ podcast + รีวิวจริง เข้าใจง่าย สร้างความน่าเชื่อถือ",
        "tags": ["Content Strategy", "Podcast Content", "Social Management", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "น่าเชื่อถือ", "work_heading_en": "",
    },
    "parapin": {
        "name": "Parapin Clinic", "category": "aesthetic", "slug": "parapin",
        "logo": "parapin",
        "desc": "คลินิกความงาม ที่เราสร้างคอนเทนต์ให้ความรู้เรื่องหัตถการเข้าใจง่าย",
        "label": "Aesthetic Clinic · Content & Ads",
        "stat_num": "1M", "stat_txt": "total views", "stat_2": "+80% engagement",
        "results": [
            ("1M", "Total Views", "ยอดวิวรวมจากทุกแพลตฟอร์ม"),
            ("+80%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("2×", "Online Booking", "การจองออนไลน์เพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์เชิงเทคนิคเข้าใจยาก ไม่ดึงดูดกลุ่มเป้าหมาย",
        "after": "คอนเทนต์ให้ความรู้เข้าใจง่าย ดึงดูดกลุ่มลูกค้าใหม่ต่อเนื่อง",
        "tags": ["Educational Content", "Content Strategy", "Social Management", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "เข้าใจง่าย", "work_heading_en": "",
    },
    "craft-dental": {
        "name": "Craft Dental Care", "category": "dental", "slug": "craft-dental",
        "logo": "craft-dental",
        "desc": "คลินิกทันตกรรม ที่เราสร้างคอนเทนต์เปรียบเทียบและรีวิวให้ตัดสินใจง่ายขึ้น",
        "label": "Dental Clinic · Content & Ads",
        "stat_num": "850K", "stat_txt": "total views", "stat_2": "+68% engagement",
        "results": [
            ("850K", "Total Views", "ยอดวิวรวมตลอดแคมเปญ"),
            ("+68%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("1.7×", "Online Booking", "การนัดหมายออนไลน์เพิ่มขึ้น"),
        ],
        "before": "ลูกค้าสับสนเรื่องตัวเลือกการรักษา ตัดสินใจยาก",
        "after": "คอนเทนต์เปรียบเทียบ + รีวิวจริง ช่วยให้ตัดสินใจง่ายขึ้น",
        "tags": ["Educational Content", "Content Strategy", "Social Management", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "ตัดสินใจง่าย", "work_heading_en": "",
    },
    "madam": {
        "name": "Madam Medical Clinic", "category": "aesthetic", "slug": "madam",
        "logo": "madam-clinic",
        "desc": "คลินิกความงาม ที่เราสร้างคอนเทนต์สม่ำเสมอให้เข้าถึงกลุ่มลูกค้าต่อเนื่องทุกเดือน",
        "label": "Aesthetic Clinic · Content & Ads",
        "stat_num": "1.3M", "stat_txt": "total views", "stat_2": "+85% engagement",
        "results": [
            ("1.3M", "Total Views", "ยอดวิวรวมจากทุกแพลตฟอร์ม"),
            ("+85%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("2.1×", "Online Booking", "การจองออนไลน์เพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์ไม่สม่ำเสมอ ขาดจังหวะการสื่อสารรายเดือน",
        "after": "คอนเทนต์สม่ำเสมอทุกเดือน สร้างการจดจำแบรนด์ต่อเนื่อง",
        "tags": ["Content Strategy", "Monthly Content", "Social Management", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "ต่อเนื่อง", "work_heading_en": "",
    },
    "ms-rehab": {
        "name": "Ms Rehab", "category": "wellness", "slug": "ms-rehab",
        "logo": "msrehab",
        "desc": "คลินิกกายภาพบำบัด ที่เราสร้างคอนเทนต์ podcast และให้คำปรึกษาเข้าถึงกลุ่มเป้าหมาย",
        "label": "Wellness Clinic · Content & Ads",
        "stat_num": "550K", "stat_txt": "total views", "stat_2": "+58% engagement",
        "results": [
            ("550K", "Total Views", "ยอดวิวรวมตลอดแคมเปญ"),
            ("+58%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("1.6×", "Online Booking", "การจองออนไลน์เพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์เชิงวิชาการเข้าถึงยาก ไม่มีความต่อเนื่อง",
        "after": "คอนเทนต์ podcast + consult เข้าใจง่าย เข้าถึงกลุ่มเป้าหมายตรงจุด",
        "tags": ["Content Strategy", "Podcast Content", "Social Management", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "เข้าถึง", "work_heading_en": "",
    },
    "jil-wink": {
        "name": "Jil Wink", "category": "aesthetic", "slug": "jil-wink",
        "logo": "jil-wink",
        "desc": "แบรนด์ผลิตภัณฑ์ผิว ที่เราสร้างคอนเทนต์ให้ความรู้เรื่องฝ้ากระเข้าถึงกลุ่มเป้าหมาย",
        "label": "Skincare Brand · Content & Ads",
        "stat_num": "950K", "stat_txt": "total views", "stat_2": "+72% engagement",
        "results": [
            ("950K", "Total Views", "ยอดวิวรวมจากทุกแพลตฟอร์ม"),
            ("+72%", "Engagement", "เพิ่มขึ้นเมื่อเทียบก่อนเริ่มงาน"),
            ("1.8×", "Online Orders", "ยอดสั่งซื้อออนไลน์เพิ่มขึ้น"),
        ],
        "before": "คอนเทนต์ขายตรงเกินไป ไม่สร้างความน่าเชื่อถือ",
        "after": "คอนเทนต์ให้ความรู้ + เคสจริง สร้างความน่าเชื่อถือและยอดขาย",
        "tags": ["Educational Content", "Content Strategy", "Social Management", "Performance Ads"],
        "work_heading_th": "คอนเทนต์ที่ ", "work_heading_accent": "น่าเชื่อถือ", "work_heading_en": "",
    },
}
